### PR TITLE
Non multiple of 8 input support for yuv420 and yuv400 inputs

### PR DESCRIPTION
**Pull request by p-chirag**
support for yuv420 for any even resolution and for yuv400 for any resolution input encoding

### CODE REVIEW

**Comment by mpeg5** [comment]
@dkozinski @dariusz-f 
Could you review and check this code is working for arbitraty resolution input?

**Comment by dariusz-f** [comment]
@mpeg5 
This change extend resolution inputs and in most of tested WebRTC cases it works correctly.
Previous resolutions that were problematic now are working good.
But in some specific cases that have odd resolution it isn't working.
In web and WebRTC usage this may be a some limitation.
But we think, now this change can be approved as an improvement step and You can consider of supporting odd resolutions in next iteration.

**Review by dariusz-f — APPROVED** [review]

**Comment by kpchoi** [comment]
> 

I am not sure why odd resolution could not be used.
@p-chirag, could you check this case? and @dariusz-f, can you describe more information how to cross-check?

**Comment by dariusz-f** [comment]
You need to generate YUV video with custom odd resolution.
For example we're using OBS software to record custom resolution video from webcamera.
And next custom resolution mp4 video can be converted to YUV in FFmpeg.
And this you can use as input to xeve to test odd resolution.

I think that also ffmpeg only can be used to prepare custom resolution raw video. But it need to be checked how to prepare correct ffmpeg command.

**Review by kpchoi — APPROVED** [review]
LGTM

**Comment by kpchoi** [comment]
According to EVC specification, I found that odd resolution cannot be supported in case of YUV420.
I think we could merge this PR anyway.

**Review by mpeg5 — APPROVED** [review]

**Pull request merged**
