### PR TITLE
Problem with similar functions of different codecs

### PR DESCRIPTION
**Pull request by Jamaika1**
Problem with similar functions of different codecs in ffmpeg compilation

### CODE REVIEW

**Comment by dkozinski** [comment]
https://github.com/mpeg5/xevd/pull/48#issuecomment-1499142162

**Comment by dariusz-f** [comment]
This change in general works correctly and when EVC is used if FFmpeg with this change all our test pass.
This change have to be integrated by using "Squash and merge"

**Review by dariusz-f — COMMENTED** [review]
src_main/sse/xevem_mc_sse.c
In this file changes are not visible because whole file is changed (probably by new style)

**Review by dkozinski — APPROVED** [review]
Looks good

**Review by dariusz-f — APPROVED** [review]

**Pull request merged**
