### PR TITLE
update DTS

### PR DESCRIPTION
**Pull request by mss-park**

### CODE REVIEW

**Review by dkozinski — APPROVED** [review]
It works for us

**Review by kpchoi — COMMENTED** [review]
@mss-park 

Can we just  explicit name for DTS and PTS in IMGB and BITB structures?

instead of imgb->ts[0], we can use imgb->pts,
instead of bitb->ts[0], we can use bitb->dts, 
and son on.

And then, we can remove ts vairables.

**Comment by dkozinski** [comment]
> @mss-park
> 
> Can we just explicit name for DTS and PTS in IMGB and BITB structures?
> 
> instead of imgb->ts[0], we can use imgb->pts, instead of bitb->ts[0], we can use bitb->dts, and son on.
> 
> And then, we can remove ts vairables.

That would be great

**Comment by mss-park** [comment]
> @mss-park
> 
> Can we just explicit name for DTS and PTS in IMGB and BITB structures?
> 
> instead of imgb->ts[0], we can use imgb->pts, instead of bitb->ts[0], we can use bitb->dts, and son on.
> 
> And then, we can remove ts vairables.

It has been changed to imgb->ts[XEVE_TS_PTS] to know the meaning.
Please check the code and merge if there is no problem.

**Comment by kpchoi** [comment]
I think that implementation of PTS and DTS has completed. we could merge this code to master,

**Pull request merged**
