### PR TITLE
Refactoring in return codes

### LINKED ISSUE #137: xeve_app returns 205 exit code on encoding successful
Hello,

When `xeve_app` finishes encoding it exits with status 205 which [means](https://github.com/mpeg5/xeve/blob/954ed6e0494cd2438fd15c717c0146e88e582b33/inc/xeve.h#L50C9-L50C28) `XEVE_OK_NO_MORE_FRM`. Is it expected behavior?
I know that encoding was OK but shouldn't the app exit with code 0 on success? That would conform with the Unix Standard.

```shell
$ xeve_app -i dnd.y4m -q 38 --keyint 128 --profile main --preset fast --threads 8 -o dnd.xeve-evc_main_fast_g128_q38.evc
XEVE: eXtra-fast Essential Video Encoder
=== Summary ====================================================================
Bitrate                           = 268.7698 kbps
Encoded frame count               = 276
Total encoding time               = 367019.000 msec, 367.019 sec
Average encoding time for a frame = 1329.779 msec
Average encoding speed            = 0.752 frames/sec
================================================================================
[oloke@pc tmp]$ echo $?
205
```

### PR DESCRIPTION
**Pull request by dariusz-f**
- Use xeve defined return codes in xeve_app
- Fix return on success in xeve_app

### CODE REVIEW

**Review by kpchoi — COMMENTED** [review]
Any reason why the application return code need to use XEVE library return code?
We can think the application code is one of example how to use XEVE library.
It might not need to use XEVE's error definitions in there.

**Comment by dariusz-f** [comment]
Currently in xeve_app code is a mix of return codes. Some are from library and some are not. So we need to decide which is preferred way and make whole implementation consistent.

**Comment by mpeg5** [comment]
@dariusz-f ,
I think the application don't have to follow xeve return values like ffmpeg.
ffmpeg is a application using codec libraries, for example libxeve.
it doesn't follow codec libraries' return value. it has own definition of return code.
Of course xeve application can define own return values internally as like ffmpeg.
But main purpose of xeve application is not commercial level application but testing use-case.
So, the application may not need own return value definition.
It is reason why the application code is using the conventional return code like 0 (zero) for success and -1 (negative) for failure.

**Comment by dariusz-f** [comment]
Ok I will refactor whole app to return 0 and -1 instead of XEVE_OK and XEVE_ERR.

**Comment by kpchoi** [comment]
@dariusz-f 
Could you check https://github.com/mpeg5/xeve/issues/137 issue?
I think there might be code returning library return code in somewhere.

**Comment by dariusz-f** [comment]
When there is no error then return is set to 0. 
Below line fixes issue #137 
https://github.com/mpeg5/xeve/blob/06f5f470b987c9192394469e6ee9c4a57be466ff/app/xeve_app.c#L1428

**Review by kpchoi — APPROVED** [review]
LGTM

**Pull request merged**
