### PR TITLE
Provided stdin input support for xeve_app

### PR DESCRIPTION
**Pull request by dkozinski**

### CODE REVIEW

**Comment by dkozinski** [comment]
In order to convert raw yuv420p to y4m and send it to xeve_app use the following command:
ffmpeg -video_size 352x288 -framerate 25 -pixel_format yuv420p -i akiyo_cif.yuv -f yuv4mpegpipe - | ./xeve_app -i stdin -o output2.evc

ffmpeg -i akiyo_cif.y4m -f yuv4mpegpipe - | ./xeve_app -i stdin -o output2.evc

**Comment by kpchoi** [comment]
@dkozinski 
I hope you to check this discussion;
https://github.com/mpeg5/xeve/issues/26
There was feedback regarding run-time error.
It might be relative to operating systems.

**Comment by dkozinski** [comment]
> @dkozinski I hope you to check this discussion; #26 There was feedback regarding run-time error. It might be relative to operating systems.



> @dkozinski I hope you to check this discussion; #26 There was feedback regarding run-time error. It might be relative to operating systems.
Yes, I've been following the discussion and we've been working on the submitted issue

**Review by dariusz-f — APPROVED** [review]
It looks that #26 is fixed, so we can approve this change.

**Review by kpchoi — APPROVED** [review]
LGTM

**Pull request merged**
