### PR TITLE
Neon code for XEVE baseline MC modules

### PR DESCRIPTION
**Pull request by washish**
Hi, Please review this PR for MC modules in XEVE Baseline

### CODE REVIEW

**Review by kpchoi — APPROVED** [review]
LGTM

**Review by mamthan — APPROVED** [review]
MC neon support added by implementing the modules with ARM Neon intrinsic. Looks good to me.

**Comment by kpchoi** [comment]
@washish 

Could you resolve conflits?

**Comment by washish** [comment]
> @washish
> 
> Could you resolve conflits?

Hi @kpchoi, I have resolved the merge conflicts.

**Pull request merged**
